### PR TITLE
Setup Travis build

### LINKED ISSUE #3: Setup repo to be in standard with other crystal-community repos
* Badges  
* README  
* CI\CD tests

### PR DESCRIPTION
**Pull request by veelenga**
Should close #3 

Example of the build: https://travis-ci.org/crystal-community/bluetooth/builds/440098299

### CODE REVIEW

**Comment by veelenga** [comment]
Build probably has got stuck. I will check it again later.

**Comment by bararchy** [comment]
@veelenga It's ok, current specs fails because the BLE part get stuck, I'll fix that in a sec, I'll remote the specs for it until we can understand why it wont work.

**Comment by bararchy** [comment]
@veelenga wait... does the CI testing ENV even have a BT device? 
maybe it makes no sense to run spec and just see if everything compiles + ameba etc..

**Comment by veelenga** [comment]
@bararchy what needs to be done to setup the app/tests? Do you use some Bluetooth emulator?

**Pull request closed without merging**
